name: Deploy to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: chat env  # 👈 This is REQUIRED to access your environment secret
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: caitlynregistry.azurecr.io
          username: caitlynregistry
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: caitlynregistry.azurecr.io/mcp-server:latest
